
- hosts: all
  become: true
  tasks:

  - name: install packages in Ubuntu and CentOS
    package:
      name: 
        - "{{tree_pkg}}"
        - "{{nvim_pkg}}"
        - "{{apache_pkg}}"
      state: latest
