
- hosts: all
  become: true
  pre_tasks:

  - name: update CentOS
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (ubuntu)
    tags: always
    apt:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks:

  - name: install packages in Ubuntu
    tags: postgres, ubuntu
    apt:
      name: 
        - postgresql
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install pakages in CentOS
    tags: centos, apache, php 
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

